name: Qactus
description: Le grand réveil peut être difficile lecture à vos risques et périls.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1
  cupertino_icons: ^1.0.0
  html_unescape: ^1.0.2
  cached_network_image: ^2.5.0
  octo_image: ^0.3.0
  shared_preferences: ^0.5.12+4
  flutter_easyloading: ^2.2.2

  # About Page
  flutter_email_sender: ^4.0.0
  package_info: ^0.4.3+4

#  Article Screen
  full_screen_image: ^1.0.2
  flutter_html: ^1.2.0
  share: ^0.6.5+4
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/loading.png
    - assets/header.png